
- hosts: es_hosts

  tasks:

    - name: Check target host
      ping:

    - name: Display distribution info
      debug:
        var: ansible_distribution

    - name: Checkout allego1.0
    - git:
        repo: 'https://kiran_suthar@bitbucket.org/brevitaz/brevitaz-allego1.0.git'
        dest: /srv/checkout

