
- hosts: 127.0.0.1
  connection: local

  tasks:

    - name: Check target host
      ping:

    - name: Checkout allego1.0
      git:
        repo: 'https://kiranBrevitaz:Init.001@bitbucket.org/brevitaz/brevitaz-allego1.0.git'
        dest: /srv/checkout

