
- hosts: localhost
  remote_user: root

  tasks:

    - name: Check target host
      ping:

    - name: Checkout allego1.0
      git:
        repo: 'https://kiran_suthar@bitbucket.org/brevitaz/brevitaz-allego1.0.git'
        dest: /srv/checkout

